version: "3.8"

services:
  product-service:
    build: ./product-service
    depends_on:
      - product-db
    environment:
      DB_HOST: product-db # container name
      DB_PORT: 5432
      DB_USER: product_user
      DB_PASSWORD: 4961025Ir
      DB_NAME: product_db
    ports:
      - "3002:3002"

  oauth-service:
    build: ./oauth-service
    depends_on:
      - oauth-db
    restart: always
    environment:
      DB_HOST: oauth-db # container name
      DB_PORT: 5432
      DB_USER: oauth_user
      DB_PASSWORD: 4961025Ir
      DB_NAME: auth
    ports:
      - "3001:3001"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - oauth-service
    restart: always

  product-db:
    image: postgres:14
    container_name: product_db
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: 4961025Ir
      POSTGRES_DB: product
    ports:
      - "5433:5432"

  oauth-db:
    image: postgres:14
    container_name: oauth_db
    environment:
      POSTGRES_USER: oauth_user
      POSTGRES_PASSWORD: 4961025Ir
      POSTGRES_DB: auth
    ports:
      - "5434:5432"
